heroku:
    stage: deploy
    only:
    - master
    script:
    - gem install dpl
    - dpl heroku git --api_key $HEROKU_API_KEY --git https://git.heroku.com/legume-back.git --strategy api --app legume-back --cleanup